name: Build Heatmap (Matrix)

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
    inputs:
      lookback_days:
        description: "Days of history (default 365)"
        required: false
        type: string

permissions:
  contents: write
  pages: write
  id-token: write

env:
  # Default if no input provided
  LOOKBACK_DAYS: ${{ inputs.lookback_days || vars.LOOKBACK_DAYS || '365' }}
  AUTHOR_EMAIL: ${{ vars.AUTHOR_EMAIL }}   # optional; applies to all unless overridden

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repo:
          - JesseConstruction/rsc_sop
          # add more here:
          # - JesseConstruction/another_repo
          # - yourorg/something_else

    steps:
      - name: Checkout this repo (heatmap host)
        uses: actions/checkout@v4

      - name: Derive file-safe name
        id: names
        shell: bash
        run: |
          SAFE=$(echo "${{ matrix.repo }}" | sed 's#/#-#g')
          echo "SAFE_NAME=$SAFE" >> $GITHUB_ENV

      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repo }}
          path: target-repo
          token: ${{ secrets.TARGET_REPO_TOKEN || github.token }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate SVG heatmap
        env:
          REPO_DIR: target-repo
          AUTHOR_EMAIL: ${{ env.AUTHOR_EMAIL }}      # or leave blank to include all
          IGNORE_MERGES: ${{ vars.IGNORE_MERGES || '1' }}
          LOOKBACK_DAYS: ${{ env.LOOKBACK_DAYS }}
          OUTPUT_SVG: public/heatmap-${{ env.SAFE_NAME }}.svg
        run: |
          python scripts/fetch_commits_and_render.py
          echo "Wrote public/heatmap-${{ env.SAFE_NAME }}.svg"

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
